### ISSUE TITLE
Image assets are not loaded via Rails asset pipeline

### ISSUE THREAD

**Issue by audionerd** [d4be4st/swagger-ui_rails#12]
Image references in [screen.css](https://github.com/d4be4st/swagger-ui_rails/blob/a11774ed2841fcb5c51751a40958f0eff0a5ffb7/app/assets/stylesheets/swagger-ui/screen.css) do not use the Rails `image-url` helper. Because of this, the Raills asset pipeline doesn't know about them, and they don't load properly (i.e.: their filenames are not updated when digest assets are used).

As a workaround, it is possible to override the image paths in the SCSS file which includes `swagger-ui`, e.g.:

`apidocs.scss`
```scss
// *= require swagger-ui

.swagger-section .swagger-ui-wrap ul#resources li.resource ul.endpoints li.endpoint ul.operations li.operation div.content div.sandbox_header span.response_throbber {
  background-image: image-url("images/throbber.gif");
}

.swagger-section .api-ic {
  background-image: image-url("images/explorer_icons.png");
}

.swagger-section #header a#logo {
  background-image: image-url("images/logo_small.png");
}
```
